language: python
python:
  - "3.7"
dist: xenial
install:
  - pipenv install --dev --deploy
addons:
  sauce_connect: true
before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - (travis_fold start unit-test-coverage; echo $ pipenv run hbcoverage; pipenv run hbcoverage; travis_fold end unit-test-coverage)
  - (travis_fold start integration-test; echo $ pipenv run hbintegrationtest; if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then pipenv run hbintegrationtest; fi; travis_fold end integration-test)
  - (travis_fold start selenium-test; echo $ pipenv run hbseleniumtest; if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then pipenv run hbseleniumtest; fi; travis_fold end selenium-test)
  - pipenv run mypy src
  - pipenv run flake8
  - diff ATTRIBUTIONS.csv <(pipenv run pip-licenses -au --from classifier -f csv)
after_script:
  - pipenv run coverage xml
  - pipenv run codecov
  - pipenv run coveralls
  - pipenv run python-codacy-coverage -r coverage.xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - pipenv lock -r > requirements.txt && fossa analyze
