language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run coverage run --branch --source=. --omit=*/migrations/* ./manage.py test
  - pipenv run codecov
  - pipenv run coveralls
