language: python
python:
- "3.6"
install:
- pip install pipenv
- pipenv install --dev
- "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
script:
- pipenv run coverage run --branch --source=. --omit=*/migrations/* ./manage.py test
after_success:
- pipenv run codecov
- pipenv run coveralls
- fossa
