language: python
python:
  - "3.6"
dist: xenial
install:
  - pip install pipenv
  - pipenv install --dev
  - >-
    curl -H 'Cache-Control: no-cache'
    https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo
    bash
addons:
  sauce_connect: true
script:
  - pipenv run coverage
  - pipenv run coverage xml
  - >-
    pipenv run mypy -p base -p associations -p districts -p leagues -p teams -p
    games -p sports_halls -p players
  - pipenv run flake8
after_success:
  - pipenv run codecov
  - pipenv run coveralls
  - pipenv run python-codacy-coverage -r coverage.xml
  - diff ATTRIBUTIONS.md <(pipenv run pip-licenses -csaum)
  - pipenv lock -r > requirements.txt && fossa
