version: "3"
# replace :latest tags with specific versions
services:
  hbscorez:
    image: djbrown/hbscorez:dev # CHANGEME
    environment:
      - DJANGO_SETTINGS_MODULE=hbscorez.settings_runtime
      - GUNICORN_WORKERS=5 # CHANGEME
    volumes:
      - /home/djbrown/Projects/hbscorez/hbscorez/settings_docker_stack.py:/settings.py:ro # CHANGEME
      - static_data:/code/static
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=8000
        - traefik.frontend.rule=Host:hbscorez.localhost # CHANGEME
  hbscorezdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: hbscorezdbuser # CHANGEME
      POSTGRES_PASSWORD: hbscorezdbpassword # CHANGEME
      POSTGRES_DB: hbscorezdb # CHANGEME
    volumes:
      - hbscorezdb_data:/var/lib/postgresql/data
  static:
    image: nginx:latest
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.frontend.rule=Host:hbscorez.localhost;PathPrefix:/static # CHANGEME
    volumes:
      - static_data:/usr/share/nginx/html/static:ro
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@localhost.de # CHANGEME
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword # CHANGEME
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.frontend.rule=Host:pgadmin.hbscorez.localhost # CHANGEME
  matomo:
    image: matomo:latest # CHANGEME
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.frontend.rule=Host:matomo.hbscorez.localhost # CHANGEME
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  matomodb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: matomodbrootpassword # CHANGEME
      MYSQL_DATABASE: matomodb # CHANGEME
      MYSQL_USER: matomodbuser # CHANGEME
      MYSQL_PASSWORD: matomodbpassword # CHANGEME
    volumes:
      - matomodb_data:/var/lib/mysql
  traefik:
    image: traefik:latest
    command:
      - --api
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - "--entrypoints=Name:https Address::443 TLS:/usr/local/share/ca-certificates/localhost/hbscorez.localhost.crt,/usr/local/share/ca-certificates/localhost/hbscorez.localhost.key;/usr/local/share/ca-certificates/localhost/pgadmin.hbscorez.localhost.crt,/usr/local/share/ca-certificates/localhost/pgadmin.hbscorez.localhost.key;/usr/local/share/ca-certificates/localhost/matomo.hbscorez.localhost.crt,/usr/local/share/ca-certificates/localhost/matomo.hbscorez.localhost.key;/usr/local/share/ca-certificates/localhost/portainer.hbscorez.localhost.crt,/usr/local/share/ca-certificates/localhost/portainer.hbscorez.localhost.key" # CHANGEME
      - --defaultentrypoints=http,https
      #- --acme
      #- --acme.storage=/etc/traefik/acme/acme.json
      #- --acme.entryPoint=https
      #- --acme.httpChallenge.entryPoint=http
      #- --acme.onHostRule=true
      #- --acme.onDemand=false
      #- --acme.email=traefik@localhost.de # CHANGEME
      - --docker
      - --docker.exposedByDefault=false
      - --docker.swarmMode
      - --docker.domain=localhost # CHANGEME
      - --docker.watch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/share/ca-certificates/:/usr/local/share/ca-certificates/
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  portainer:
    image: portainer/portainer:latest
    command:
      - --no-analytics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.port=9000
        - traefik.frontend.rule=Host:portainer.hbscorez.localhost # CHANGEME
volumes:
  ? hbscorezdb_data
  ? static_data
  ? pgadmin_data
  ? matomodb_data
  ? portainer_data
